In [ ]:
import pandas as pd

In [3]:
df= pd.read_csv('/home/harshit/csv files/Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [6]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges']

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [7]:
df.shape

(7043, 21)

In [8]:
X= df.drop(['Churn', 'customerID'], axis=1)
y= df['Churn']

In [9]:
X_cat= X.select_dtypes(include=['object'])
X_num= X.select_dtypes(exclude=['object'])

In [10]:
X_cat

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,Female,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check
1,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check
2,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
3,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic)
4,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check
7039,Female,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic)
7040,Female,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check
7041,Male,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check
7042,Male,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic)

In [11]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', dtype='int')
le= LabelEncoder()

In [12]:
ohe_features=X_cat[['MultipleLines', 'InternetService', 'Contract', 'PaymentMethod']]
ohe.fit(ohe_features)
ohe_features_names=ohe.get_feature_names_out(ohe_features.columns)

In [13]:
label_feateres=X_cat.drop(['MultipleLines', 'InternetService',  'Contract', 'PaymentMethod'], axis=1)

In [14]:
for i in label_feateres:
    X_cat[i]=le.fit_transform(label_feateres[i])
X_cat['StreamingMovies']=le.fit_transform(X_cat['StreamingMovies'])

In [15]:
X_cat

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,0,1,0,0,No phone service,DSL,0,2,0,0,0,0,Month-to-month,1,Electronic check
1,1,0,0,1,No,DSL,2,0,2,0,0,0,One year,0,Mailed check
2,1,0,0,1,No,DSL,2,2,0,0,0,0,Month-to-month,1,Mailed check
3,1,0,0,0,No phone service,DSL,2,0,2,2,0,0,One year,0,Bank transfer (automatic)
4,0,0,0,1,No,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Electronic check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,1,1,1,Yes,DSL,2,0,2,2,2,2,One year,1,Mailed check
7039,0,1,1,1,Yes,Fiber optic,0,2,2,0,2,2,One year,1,Credit card (automatic)
7040,0,1,1,0,No phone service,DSL,2,0,0,0,0,0,Month-to-month,1,Electronic check
7041,1,1,0,1,Yes,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Mailed check
7042,1,0,0,1,No,Fiber optic,2,0,2,2,2,2,Two year,1,Bank transfer (automatic)

In [16]:
ohe_df=pd.DataFrame(ohe.transform(ohe_features), columns=ohe_features_names)
X_cat=X_cat.drop(['MultipleLines', 'InternetService',  'Contract', 'PaymentMethod'], axis=1)
X_cat=pd.concat([X_cat, ohe_df], axis=1)
X_cat

,gender,Partner,Dependents,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0,0,2,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
1,1,0,0,1,2,0,2,0,0,0,...,1,0,0,0,1,0,0,0,0,1
2,1,0,0,1,2,2,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
3,1,0,0,0,2,0,2,2,0,0,...,1,0,0,0,1,0,1,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,1,1,1,2,0,2,2,2,2,...,1,0,0,0,1,0,0,0,0,1
7039,0,1,1,1,0,2,2,0,2,2,...,0,1,0,0,1,0,0,1,0,0
7040,0,1,1,0,2,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
7041,1,1,0,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,1,0,0,1,2,0,2,2,2,2,...,0,1,0,0,0,1,1,0,0,0

In [17]:
X_final= pd.concat([X_num, X_cat], axis=1)
X_final['TotalCharges']=X_final['TotalCharges'].fillna(0)
X_final.isnull().sum()

SeniorCitizen                              0
tenure                                     0
MonthlyCharges                             0
TotalCharges                               0
gender                                     0
Partner                                    0
Dependents                                 0
PhoneService                               0
OnlineSecurity                             0
OnlineBackup                               0
DeviceProtection                           0
TechSupport                                0
StreamingTV                                0
StreamingMovies                            0
PaperlessBilling                           0
MultipleLines_No                           0
MultipleLines_No phone service             0
MultipleLines_Yes                          0
InternetService_DSL                        0
InternetService_Fiber optic                0
InternetService_No                         0
Contract_Month-to-month                    0
Contract_One year                          0
Contract_Two year                          0
PaymentMethod_Bank transfer (automatic)    0
PaymentMethod_Credit card (automatic)      0
PaymentMethod_Electronic check             0
PaymentMethod_Mailed check                 0
dtype: int64

In [ ]:
y=le.fit_transform(y)
y

array([0, 0, 1, ..., 0, 1, 0], shape=(7043,))

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier
from sklearn.model_selection import RandomizedSearchCV, cross_validate

In [ ]:
models={
    'rf': RandomForestClassifier(),
    'gbc': GradientBoostingClassifier(),
    'hgbc': HistGradientBoostingClassifier()
    
}
params={
    'rf': {'n_estimators': [100, 200,250], 'max_depth': [None, 10, 20],'min_samples_leaf': [2, 5, 10]},
    'gbc': {'n_estimators': [100,200,250], 'learning_rate': [ 0.1,0.2,0.5,0.8],'min_samples_leaf': [2, 5, 10]},
    'hgbc': {'max_iter': [100, 200,250], 'max_depth': [None, 10],'min_samples_leaf': [2, 5, 10]}
}

In [ ]:
for model,value in models.items():
    classifier=RandomizedSearchCV(models[model],params[model], cv=5, n_iter=10)
    classifier.fit(X_train, y_train)
    print(f'Best parameters for {model}: {classifier.best_params_}')
    print(f'Best score for {model}: {classifier.best_score_}')

Best parameters for rf: {'n_estimators': 100, 'min_samples_leaf': 10, 'max_depth': 20}
Best score for rf: 0.8001390068731176
Best parameters for gbc: {'n_estimators': 100, 'min_samples_leaf': 5, 'learning_rate': 0.2}
Best score for gbc: 0.7972997678490656
Best parameters for hgbc: {'min_samples_leaf': 2, 'max_iter': 100, 'max_depth': None}
Best score for hgbc: 0.7923306661455223

In [ ]:
def train(model,X_train,y_train,y_test):
    cross_validate(model, X_train, y_train, cv=5, scoring='accuracy')
    model.fit(X_train,y_train)
    score=model.score(X_test,y_test)
    print('Score of the model:', score)

In [66]:
rf=RandomForestClassifier(n_estimators=100, max_depth=10, min_samples_leaf=5)
train(rf, X_train, y_train, y_test)

Score of the model: 0.8034066713981547

In [70]:
gbc=GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, min_samples_leaf=2)
train(gbc, X_train, y_train, y_test)

Score of the model: 0.7955997161107168

In [69]:
hgbc=HistGradientBoostingClassifier(max_iter=100, max_depth=5, min_samples_leaf=2)
train(hgbc, X_train, y_train, y_test)

Score of the model: 0.794889992902768

In [67]:
y_pred=rf.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [83]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
cm= confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[935 100]
 [177 197]]

In [85]:
print('Classification Report:')
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1035
           1       0.66      0.53      0.59       374

    accuracy                           0.80      1409
   macro avg       0.75      0.72      0.73      1409
weighted avg       0.79      0.80      0.80      1409